# Generated by Django 5.2.1 on 2025-05-23 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('POULES', 'Phase de poules'), ('HUITIEME', 'Huitième de finale'), ('QUART', 'Quart de finale'), ('DEMI', 'Demi-finale'), ('FINALE', 'Finale'), ('PETITE_FINALE', 'Petite finale')], default='POULES', max_length=20)),
                ('numero_match', models.IntegerField(default=1)),
                ('date_heure', models.DateTimeField(blank=True, null=True)),
                ('terrain', models.CharField(blank=True, default='Terrain principal', max_length=100)),
                ('score_domicile', models.IntegerField(blank=True, null=True)),
                ('score_exterieur', models.IntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('A_VENIR', 'À venir'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('REPORTE', 'Reporté')], default='A_VENIR', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('equipe_domicile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_domicile', to='core.equipe')),
                ('equipe_exterieur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_exterieur', to='core.equipe')),
                ('tournoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs', to='core.tournoi')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matchs',
                'ordering': ['date_heure', 'numero_match'],
            },
        ),
        migrations.CreateModel(
            name='Classement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchs_joues', models.IntegerField(default=0)),
                ('victoires', models.IntegerField(default=0)),
                ('nuls', models.IntegerField(default=0)),
                ('defaites', models.IntegerField(default=0)),
                ('buts_pour', models.IntegerField(default=0)),
                ('buts_contre', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=1)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipe')),
                ('tournoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classements', to='core.tournoi')),
            ],
            options={
                'verbose_name': 'Classement',
                'verbose_name_plural': 'Classements',
                'ordering': ['-points', '-buts_pour', 'buts_contre'],
                'unique_together': {('tournoi', 'equipe')},
            },
        ),
    ]
